
## ======================================================================
## Pipeline for GPDB6 PL/JAVA GPPKG
## ======================================================================

groups:
- name: All
  jobs:
    - pljava_centos7_build
    - pljava_centos6_build
    - pljava_ubuntu16_build
    - pljava_sles11_build
    - pljava_centos7_test_jdk8
    - pljava_centos6_test_jdk8
    - pljava_ubuntu16_test_jdk8
    - pljava_sles11_test_jdk8
    - pljava_centos7_test_jdk11
    - pljava_centos6_test_jdk11
    - pljava_ubuntu16_test_jdk11
    - pljava_sles11_test_jdk11
    - pljava_centos7_release
    - pljava_centos6_release
    - pljava_ubuntu16_release
    - pljava_sles11_release
    - pljava_centos7_test_release_jdk8
    - pljava_centos6_test_release_jdk8
    - pljava_ubuntu16_test_release_jdk8
    - pljava_sles11_test_release_jdk8
    - pljava_centos7_test_release_jdk11
    - pljava_centos6_test_release_jdk11
    - pljava_ubuntu16_test_release_jdk11
    - pljava_sles11_test_release_jdk11

- name: GPDB6
  jobs:
    - pljava_centos7_build
    - pljava_centos6_build
    - pljava_ubuntu16_build
    - pljava_sles11_build
    - pljava_centos7_test_jdk8
    - pljava_centos6_test_jdk8
    - pljava_ubuntu16_test_jdk8
    - pljava_sles11_test_jdk8
    - pljava_centos7_test_jdk11
    - pljava_centos6_test_jdk11
    - pljava_ubuntu16_test_jdk11
    - pljava_sles11_test_jdk11

- name: RELEASE
  jobs:
    - pljava_centos7_release
    - pljava_centos6_release
    - pljava_ubuntu16_release
    - pljava_sles11_release
    - pljava_centos7_test_release_jdk8
    - pljava_centos6_test_release_jdk8
    - pljava_ubuntu16_test_release_jdk8
    - pljava_sles11_test_release_jdk8
    - pljava_centos7_test_release_jdk11
    - pljava_centos6_test_release_jdk11
    - pljava_ubuntu16_test_release_jdk11
    - pljava_sles11_test_release_jdk11

resource_types:
- name: gcs
  type: docker-image
  source:
    repository: frodenas/gcs-resource

## ======================================================================
## resources
## ======================================================================
resources:

## GPDB6 resource
##
- name: bin_gpdb_centos6
  type: s3
  source:
    access_key_id: {{bucket-access-key-id}}
    bucket: {{bucket-name}}
    region_name: {{aws-region}}
    secret_access_key: {{bucket-secret-access-key}}
    versioned_file: {{bin_gpdb_centos_versioned_file}}

- name: bin_gpdb_centos7
  type: s3
  source:
    access_key_id: {{bucket-access-key-id}}
    bucket: {{bucket-name}}
    region_name: {{aws-region}}
    secret_access_key: {{bucket-secret-access-key}}
    versioned_file: {{bin_gpdb_centos7_versioned_file}}

- name: bin_gpdb_sles11
  type: s3
  source:
    access_key_id: {{bucket-access-key-id}}
    bucket: {{bucket-name}}
    region_name: {{aws-region}}
    secret_access_key: {{bucket-secret-access-key}}
    versioned_file: {{bin_gpdb_sles11_versioned_file}}

- name: bin_gpdb_ubuntu16
  type: s3
  source:
    access_key_id: {{bucket-access-key-id}}
    bucket: {{bucket-name}}
    region_name: {{aws-region}}
    secret_access_key: {{bucket-secret-access-key}}
    versioned_file: {{compiled_bits_ubuntu16_versioned_file}}


- name: pljava_centos6_img
  type: docker-image
  source:
    repository: pivotaldata/centos-gpdb-dev
    tag: '6-gcc6.2-llvm3.7'

- name: pljava_centos7_img
  type: docker-image
  source:
    repository: pivotaldata/centos-gpdb-dev
    tag: '7-gcc6.2-llvm3.7'

- name: pljava_sles11_img
  type: docker-image
  source:
    repository: pivotaldata/sles-gpdb-dev
    tag: '11-beta'

- name: pljava_ubuntu16_img
  type: docker-image
  source:
    repository: pivotaldata/ubuntu-gpdb-dev
    tag: '16.04'

- name: pljava_src
  type: git
  source:
    branch: gpdb6_release
    uri: https://github.com/greenplum-db/pljava.git

- name: gpdb_src
  type: git
  source:
    branch: {{gpdb-git-branch}}
    uri: https://github.com/greenplum-db/gpdb.git

- name: release_trigger
  type: git
  source:
    branch: gpdb6_release
    uri: https://github.com/greenplum-db/pljava.git
    tag_filter: 2.*

- name: pljava_gpdb_centos6_build
  type: gcs
  source:
    bucket: {{pl-bucket-name}}
    region_name: us-west-1
    json_key: {{gcs-read-write-service-account-key}}
    versioned_file: build/gpdb6/pljava/centos6/pljava-centos.gppkg

- name: pljava_gpdb_centos7_build
  type: gcs
  source:
    bucket: {{pl-bucket-name}}
    region_name: us-west-1
    json_key: {{gcs-read-write-service-account-key}}
    versioned_file: build/gpdb6/pljava/centos7/pljava-centos.gppkg

- name: pljava_gpdb_sles11_build
  type: gcs
  source:
    bucket: {{pl-bucket-name}}
    region_name: us-west-1
    json_key: {{gcs-read-write-service-account-key}}
    versioned_file: build/gpdb6/pljava/sles11/pljava-sles.gppkg

- name: pljava_gpdb_ubuntu16_build
  type: gcs
  source:
    bucket: {{pl-bucket-name}}
    region_name: us-west-1
    json_key: {{gcs-read-write-service-account-key}}
    versioned_file: build/gpdb6/pljava/ubuntu16/pljava-ubuntu.gppkg

- name: pljava_gpdb_centos6_release
  type: gcs
  source:
    bucket: {{pl-bucket-name}}
    region_name: us-west-1
    json_key: {{gcs-read-write-service-account-key}}
    regexp: release/gpdb6/pljava/pljava-(.*)-rhel6-x86_64.gppkg

- name: pljava_gpdb_centos7_release
  type: gcs
  source:
    bucket: {{pl-bucket-name}}
    region_name: us-west-1
    json_key: {{gcs-read-write-service-account-key}}
    regexp: release/gpdb6/pljava/pljava-(.*)-rhel7-x86_64.gppkg

- name: pljava_gpdb_sles11_release
  type: gcs
  source:
    bucket: {{pl-bucket-name}}
    region_name: us-west-1
    json_key: {{gcs-read-write-service-account-key}}
    regexp: release/gpdb6/pljava/pljava-(.*)-sles11-x86_64.gppkg

- name: pljava_gpdb_ubuntu16_release
  type: gcs
  source:
    bucket: {{pl-bucket-name}}
    region_name: us-west-1
    json_key: {{gcs-read-write-service-account-key}}
    regexp: release/gpdb6/pljava/pljava-(.*)-ubuntu16-x86_64.gppkg

- name: pljava_gpdb_centos6_release_candidate
  type: gcs
  source:
    bucket: {{pl-bucket-name}}
    region_name: us-west-1
    json_key: {{gcs-read-write-service-account-key}}
    regexp: release_candidate/gpdb6/pljava/pljava-(.*)-rhel6-x86_64.gppkg

- name: pljava_gpdb_centos7_release_candidate
  type: gcs
  source:
    bucket: {{pl-bucket-name}}
    region_name: us-west-1
    json_key: {{gcs-read-write-service-account-key}}
    regexp: release_candidate/gpdb6/pljava/pljava-(.*)-rhel7-x86_64.gppkg

- name: pljava_gpdb_sles11_release_candidate
  type: gcs
  source:
    bucket: {{pl-bucket-name}}
    region_name: us-west-1
    json_key: {{gcs-read-write-service-account-key}}
    regexp: release_candidate/gpdb6/pljava/pljava-(.*)-sles11-x86_64.gppkg

- name: pljava_gpdb_ubuntu16_release_candidate
  type: gcs
  source:
    bucket: {{pl-bucket-name}}
    region_name: us-west-1
    json_key: {{gcs-read-write-service-account-key}}
    regexp: release_candidate/gpdb6/pljava/pljava-(.*)-ubuntu16-amd64.gppkg

- name: jdk11_tgz
  type: s3
  source:
    bucket: {{pl-bucket-name}}
    region_name: {{aws-region}}
    access_key_id: {{bucket-access-key-id}}
    secret_access_key: {{bucket-secret-access-key}}
    versioned_file: dependancy/openjdk-11.0.1_linux-x64_bin.tar.gz


jobs:
## GPDB6 PL/Java Jobs
##
- name: pljava_centos7_build
  plan:
  - aggregate:
    - get: pljava_src
      trigger: true
    - get: bin_gpdb
      resource: bin_gpdb_centos7
      trigger: true
    - get: pljava_centos7_img
    - get: gpdb_src
  - aggregate:
    - task: pljava_gpdb_build
      file: pljava_src/concourse/tasks/build_pljava.yml
      image: pljava_centos7_img
      params:
        OSVER: centos7
        PL_GP_VERSION: "6.0"
        JDK_VERSION: 8
  - aggregate:
    - put: pljava_gpdb_centos7_build
      params:
        file: pljava_gppkg/pljava-*.gppkg

- name: pljava_centos6_build
  plan:
  - aggregate:
    - get: pljava_src
      trigger: true
    - get: bin_gpdb
      resource: bin_gpdb_centos6
      trigger: true
    - get: pljava_centos6_img
    - get: gpdb_src
  - aggregate:
    - task: pljava_gpdb_build
      file: pljava_src/concourse/tasks/build_pljava.yml
      image: pljava_centos6_img
      params:
        OSVER: centos6
        PL_GP_VERSION: "6.0"
        JDK_VERSION: 8
  - aggregate:
    - put: pljava_gpdb_centos6_build
      params:
        file: pljava_gppkg/pljava-*.gppkg

- name: pljava_sles11_build
  plan:
  - aggregate:
    - get: pljava_src
      trigger: true
    - get: bin_gpdb
      resource: bin_gpdb_sles11
      trigger: true
    - get: pljava_sles11_img
    - get: gpdb_src
  - aggregate:
    - task: pljava_gpdb_build
      file: pljava_src/concourse/tasks/build_pljava.yml
      image: pljava_sles11_img
      params:
        OSVER: suse11
        PL_GP_VERSION: "6.0"
        JDK_VERSION: 8
  - aggregate:
    - put: pljava_gpdb_sles11_build
      params:
        file: pljava_gppkg/pljava-*.gppkg

- name: pljava_ubuntu16_build
  plan:
  - aggregate:
    - get: pljava_src
      trigger: true
    - get: bin_gpdb
      resource: bin_gpdb_ubuntu16
      trigger: true
    - get: pljava_ubuntu16_img
    - get: gpdb_src
  - aggregate:
    - task: pljava_gpdb_build
      file: pljava_src/concourse/tasks/build_pljava.yml
      image: pljava_ubuntu16_img
      params:
        OSVER: ubuntu16
        PL_GP_VERSION: "6.0"
        JDK_VERSION: 8
  - aggregate:
    - put: pljava_gpdb_ubuntu16_build
      params:
        file: pljava_gppkg/pljava-*.gppkg

- name: pljava_centos7_test_jdk8
  plan:
  - aggregate:
    - get: pljava_src
      passed: [pljava_centos7_build]
    - get: pljava_bin
      resource: pljava_gpdb_centos7_build
      trigger: true
    - get: bin_gpdb
      resource: bin_gpdb_centos7
    - get: pljava_centos7_img
    - get: gpdb_src
  - aggregate:
    - task: test_pljava
      file: pljava_src/concourse/tasks/test_pljava.yml
      image: pljava_centos7_img
      params:
        OSVER: centos7
        PL_GP_VERSION: "6.0"
        JDK_VERSION: 8

- name: pljava_centos6_test_jdk8
  plan:
  - aggregate:
    - get: pljava_src
      passed: [pljava_centos6_build]
    - get: pljava_bin
      resource: pljava_gpdb_centos6_build
      trigger: true
    - get: bin_gpdb
      resource: bin_gpdb_centos6
    - get: pljava_centos6_img
    - get: gpdb_src
  - aggregate:
    - task: test_pljava
      file: pljava_src/concourse/tasks/test_pljava.yml
      image: pljava_centos6_img
      params:
        OSVER: centos6
        PL_GP_VERSION: "6.0"
        JDK_VERSION: 8

- name: pljava_sles11_test_jdk8
  plan:
  - aggregate:
    - get: pljava_src
      passed: [pljava_sles11_build]
    - get: pljava_bin
      resource: pljava_gpdb_sles11_build
      trigger: true
    - get: bin_gpdb
      resource: bin_gpdb_sles11
    - get: pljava_sles11_img
    - get: gpdb_src
  - aggregate:
    - task: test_pljava
      file: pljava_src/concourse/tasks/test_pljava.yml
      image: pljava_sles11_img
      params:
        OSVER: suse11
        PL_GP_VERSION: "6.0"
        JDK_VERSION: 8

- name: pljava_ubuntu16_test_jdk8
  plan:
  - aggregate:
    - get: pljava_src
      passed: [pljava_ubuntu16_build]
    - get: pljava_bin
      resource: pljava_gpdb_ubuntu16_build
      trigger: true
    - get: bin_gpdb
      resource: bin_gpdb_ubuntu16
    - get: pljava_ubuntu16_img
    - get: gpdb_src
  - aggregate:
    - task: test_pljava
      file: pljava_src/concourse/tasks/test_pljava.yml
      image: pljava_ubuntu16_img
      params:
        OSVER: ubuntu16
        PL_GP_VERSION: "6.0"
        JDK_VERSION: 8

- name: pljava_centos7_test_jdk11
  plan:
  - aggregate:
    - get: pljava_src
      passed: [pljava_centos7_build]
    - get: pljava_bin
      resource: pljava_gpdb_centos7_build
      trigger: true
    - get: bin_gpdb
      resource: bin_gpdb_centos7
    - get: pljava_centos7_img
    - get: gpdb_src
  - aggregate:
    - task: test_pljava
      file: pljava_src/concourse/tasks/test_pljava.yml
      image: pljava_centos7_img
      params:
        OSVER: centos7
        PL_GP_VERSION: "6.0"
        JDK_VERSION: 11

- name: pljava_centos6_test_jdk11
  plan:
  - aggregate:
    - get: pljava_src
      passed: [pljava_centos6_build]
    - get: pljava_bin
      resource: pljava_gpdb_centos6_build
      trigger: true
    - get: jdk_bin
      resource: jdk11_tgz
    - get: bin_gpdb
      resource: bin_gpdb_centos6
    - get: pljava_centos6_img
    - get: gpdb_src
  - aggregate:
    - task: test_pljava
      file: pljava_src/concourse/tasks/test_pljava_jdk.yml
      image: pljava_centos6_img
      params:
        OSVER: centos6
        PL_GP_VERSION: "6.0"
        JDK_VERSION: 11

- name: pljava_sles11_test_jdk11
  plan:
  - aggregate:
    - get: pljava_src
      passed: [pljava_sles11_build]
    - get: pljava_bin
      resource: pljava_gpdb_sles11_build
      trigger: true
    - get: bin_gpdb
      resource: bin_gpdb_sles11
    - get: pljava_sles11_img
    - get: gpdb_src
  - aggregate:
    - task: test_pljava
      file: pljava_src/concourse/tasks/test_pljava.yml
      image: pljava_sles11_img
      params:
        OSVER: suse11
        PL_GP_VERSION: "6.0"
        JDK_VERSION: 11

- name: pljava_ubuntu16_test_jdk11
  plan:
  - aggregate:
    - get: pljava_src
      passed: [pljava_ubuntu16_build]
    - get: pljava_bin
      resource: pljava_gpdb_ubuntu16_build
      trigger: true
    - get: bin_gpdb
      resource: bin_gpdb_ubuntu16
    - get: pljava_ubuntu16_img
    - get: gpdb_src
  - aggregate:
    - task: test_pljava
      file: pljava_src/concourse/tasks/test_pljava.yml
      image: pljava_ubuntu16_img
      params:
        OSVER: ubuntu16
        PL_GP_VERSION: "6.0"
        JDK_VERSION: 11

- name: pljava_centos7_test_release_jdk8
  plan:
  - aggregate:
    - get: pljava_src
    - get: pljava_bin
      resource: pljava_gpdb_centos7_release
    - get: bin_gpdb
      resource: bin_gpdb_centos7
      trigger: true
    - get: pljava_centos7_img
    - get: gpdb_src
  - aggregate:
    - task: test_pljava
      file: pljava_src/concourse/tasks/test_pljava.yml
      image: pljava_centos7_img
      params:
        OSVER: centos7
        PL_GP_VERSION: "6.0"
        JDK_VERSION: 8

- name: pljava_centos6_test_release_jdk8
  plan:
  - aggregate:
    - get: pljava_src
    - get: pljava_bin
      resource: pljava_gpdb_centos6_release
    - get: bin_gpdb
      resource: bin_gpdb_centos6
      trigger: true
    - get: pljava_centos6_img
    - get: gpdb_src
  - aggregate:
    - task: test_pljava
      file: pljava_src/concourse/tasks/test_pljava.yml
      image: pljava_centos6_img
      params:
        OSVER: centos6
        PL_GP_VERSION: "6.0"
        JDK_VERSION: 8

- name: pljava_sles11_test_release_jdk8
  plan:
  - aggregate:
    - get: pljava_src
    - get: pljava_bin
      resource: pljava_gpdb_sles11_release
    - get: bin_gpdb
      resource: bin_gpdb_sles11
      trigger: true
    - get: pljava_sles11_img
    - get: gpdb_src
  - aggregate:
    - task: test_pljava
      file: pljava_src/concourse/tasks/test_pljava.yml
      image: pljava_sles11_img
      params:
        OSVER: suse11
        PL_GP_VERSION: "6.0"
        JDK_VERSION: 8

- name: pljava_ubuntu16_test_release_jdk8
  plan:
  - aggregate:
    - get: pljava_src
    - get: pljava_bin
      resource: pljava_gpdb_ubuntu16_release
    - get: bin_gpdb
      resource: bin_gpdb_ubuntu16
      trigger: true
    - get: pljava_ubuntu16_img
    - get: gpdb_src
  - aggregate:
    - task: test_pljava
      file: pljava_src/concourse/tasks/test_pljava.yml
      image: pljava_ubuntu16_img
      params:
        OSVER: ubuntu16
        PL_GP_VERSION: "6.0"
        JDK_VERSION: 8

- name: pljava_centos7_test_release_jdk11
  plan:
  - aggregate:
    - get: pljava_src
    - get: pljava_bin
      resource: pljava_gpdb_centos7_release
    - get: bin_gpdb
      resource: bin_gpdb_centos7
      trigger: true
    - get: pljava_centos7_img
    - get: gpdb_src
  - aggregate:
    - task: test_pljava
      file: pljava_src/concourse/tasks/test_pljava.yml
      image: pljava_centos7_img
      params:
        OSVER: centos7
        PL_GP_VERSION: "6.0"
        JDK_VERSION: 11

- name: pljava_centos6_test_release_jdk11
  plan:
  - aggregate:
    - get: pljava_src
    - get: pljava_bin
      resource: pljava_gpdb_centos6_release
    - get: jdk_bin
      resource: jdk11_tgz
    - get: bin_gpdb
      resource: bin_gpdb_centos6
      trigger: true
    - get: pljava_centos6_img
    - get: gpdb_src
  - aggregate:
    - task: test_pljava
      file: pljava_src/concourse/tasks/test_pljava_jdk.yml
      image: pljava_centos6_img
      params:
        OSVER: centos6
        PL_GP_VERSION: "6.0"
        JDK_VERSION: 11

- name: pljava_sles11_test_release_jdk11
  plan:
  - aggregate:
    - get: pljava_src
    - get: pljava_bin
      resource: pljava_gpdb_sles11_release
    - get: bin_gpdb
      resource: bin_gpdb_sles11
      trigger: true
    - get: pljava_sles11_img
    - get: gpdb_src
  - aggregate:
    - task: test_pljava
      file: pljava_src/concourse/tasks/test_pljava.yml
      image: pljava_sles11_img
      params:
        OSVER: suse11
        PL_GP_VERSION: "6.0"
        JDK_VERSION: 11

- name: pljava_ubuntu16_test_release_jdk11
  plan:
  - aggregate:
    - get: pljava_src
    - get: pljava_bin
      resource: pljava_gpdb_ubuntu16_release
    - get: bin_gpdb
      resource: bin_gpdb_ubuntu16
      trigger: true
    - get: pljava_ubuntu16_img
    - get: gpdb_src
  - aggregate:
    - task: test_pljava
      file: pljava_src/concourse/tasks/test_pljava.yml
      image: pljava_ubuntu16_img
      params:
        OSVER: ubuntu16
        PL_GP_VERSION: "6.0"
        JDK_VERSION: 11

- name: pljava_centos7_release
  plan:
  - aggregate:
    - get: pljava_src
    - get: release_trigger
      trigger: true
    - get: pljava_bin
      resource: pljava_gpdb_centos7_build
    - get: pljava_centos7_img
  - aggregate:
    - task: release_pljava
      file: pljava_src/concourse/tasks/release_pljava.yml
      image: pljava_centos7_img
      params:
        OSVER: centos7
        PL_GP_VERSION: "6.0"
  - aggregate:
    - put: pljava_gpdb_centos7_release_candidate
      params:
        file: pljava_gppkg/pljava-*.gppkg

- name: pljava_centos6_release
  plan:
  - aggregate:
    - get: pljava_src
    - get: release_trigger
      trigger: true
    - get: pljava_bin
      resource: pljava_gpdb_centos6_build
    - get: pljava_centos6_img
  - aggregate:
    - task: release_pljava
      file: pljava_src/concourse/tasks/release_pljava.yml
      image: pljava_centos6_img
      params:
        OSVER: centos6
        PL_GP_VERSION: "6.0"
  - aggregate:
    - put: pljava_gpdb_centos6_release_candidate
      params:
        file: pljava_gppkg/pljava-*.gppkg

- name: pljava_sles11_release
  plan:
  - aggregate:
    - get: pljava_src
    - get: release_trigger
      trigger: true
    - get: pljava_bin
      resource: pljava_gpdb_sles11_build
    - get: pljava_sles11_img
  - aggregate:
    - task: release_pljava
      file: pljava_src/concourse/tasks/release_pljava.yml
      image: pljava_sles11_img
      params:
        OSVER: suse11
        PL_GP_VERSION: "6.0"
  - aggregate:
    - put: pljava_gpdb_sles11_release_candidate
      params:
        file: pljava_gppkg/pljava-*.gppkg

- name: pljava_ubuntu16_release
  plan:
  - aggregate:
    - get: pljava_src
    - get: release_trigger
      trigger: true
    - get: pljava_bin
      resource: pljava_gpdb_ubuntu16_build
    - get: pljava_ubuntu16_img
  - aggregate:
    - task: release_pljava
      file: pljava_src/concourse/tasks/release_pljava.yml
      image: pljava_ubuntu16_img
      params:
        OSVER: ubuntu16
        PL_GP_VERSION: "6.0"
  - aggregate:
    - put: pljava_gpdb_ubuntu16_release_candidate
      params:
        file: pljava_gppkg/pljava-*.gppkg

