## ======================================================================
## Pipeline for GPDB4 PL/R GPPKG
## ======================================================================

groups:
- name: All
  jobs:
    - pljava_gpdb4_centos5_build
    - pljava_gpdb4_sles11_build
    - pljava_gpdb4_centos5_test
    - pljava_gpdb4_sles11_test
    - pljava_gpdb4_centos5_release
    - pljava_gpdb4_sles11_release
    - pljava_gpdb4_centos5_release_test
    - pljava_gpdb4_sles11_release_test

- name: GPDB4
  jobs:
    - pljava_gpdb4_centos5_build
    - pljava_gpdb4_sles11_build
    - pljava_gpdb4_centos5_test
    - pljava_gpdb4_sles11_test

- name: RELEASE
  jobs:
    - pljava_gpdb4_centos5_release
    - pljava_gpdb4_sles11_release
    - pljava_gpdb4_centos5_release_test
    - pljava_gpdb4_sles11_release_test

## ======================================================================
## resources
## ======================================================================
resources:

## GPDB4 resource
##
- name: bin_gpdb4_centos5
  type: s3
  source:
    bucket: {{bucket-name}}
    region_name: {{aws-region}}
    access_key_id: {{bucket-access-key-id}}
    secret_access_key: {{bucket-secret-access-key}}
    versioned_file: bin_gpdb_centos/bin_gpdb.tar.gz

- name: bin_gpdb4_sles11
  type: s3
  source:
    bucket: {{bucket-name}}
    region_name: {{aws-region}}
    access_key_id: {{bucket-access-key-id}}
    secret_access_key: {{bucket-secret-access-key}}
    versioned_file: bin_gpdb_sles/bin_gpdb.tar.gz

- name: gpdb_src
  type: git
  source:
    branch: 5X_STABLE
    uri: https://github.com/greenplum-db/gpdb.git

- name: pljava_src
  type: git
  source:
    branch: gpdb4_release
    uri: https://github.com/greenplum-db/pljava.git

- name: release_src
  type: git
  source:
    branch: gpdb4_release
    uri: https://github.com/greenplum-db/pljava.git
    tag_filter: 1.3.*

- name: jre
  type: s3
  source:
    bucket: noarch-toolchain-snowflakes
    region_name: {{aws-region}}
    access_key_id: {{bucket-access-key-id}}
    secret_access_key: {{bucket-secret-access-key}}
    versioned_file: jre/jre-8u172-linux-x64.tar.gz

- name: pljava_centos5_img
  type: docker-image
  source:
    repository: pivotaldata/centos-gpdb-dev
    tag: '5'

- name: pljava_gpdb4_centos5_build
  type: s3
  source:
    bucket: {{pl-bucket-name}}
    region_name: {{aws-region}}
    access_key_id: {{bucket-access-key-id}}
    secret_access_key: {{bucket-secret-access-key}}
    versioned_file: build/gpdb4/pljava/centos5/pljava-centos.gppkg

- name: pljava_gpdb4_sles11_build
  type: s3
  source:
    bucket: {{pl-bucket-name}}
    region_name: {{aws-region}}
    access_key_id: {{bucket-access-key-id}}
    secret_access_key: {{bucket-secret-access-key}}
    versioned_file: build/gpdb4/pljava/sles11/pljava-suse11.gppkg

- name: pljava_gpdb4_centos5_release
  type: s3
  source:
    bucket: {{pl-bucket-name}}
    region_name: {{aws-region}}
    access_key_id: {{bucket-access-key-id}}
    secret_access_key: {{bucket-secret-access-key}}
    regexp: release/gpdb4/pljava/pljava-(.*)-rhel5-x86_64.gppkg

- name: pljava_gpdb4_sles11_release
  type: s3
  source:
    bucket: {{pl-bucket-name}}
    region_name: {{aws-region}}
    access_key_id: {{bucket-access-key-id}}
    secret_access_key: {{bucket-secret-access-key}}
    regexp: release/gpdb4/pljava/pljava-(.*)-sles11-x86_64.gppkg

- name: pljava_gpdb4_centos5_release_candidate
  type: s3
  source:
    bucket: {{pl-bucket-name}}
    region_name: {{aws-region}}
    access_key_id: {{bucket-access-key-id}}
    secret_access_key: {{bucket-secret-access-key}}
    regexp: release_candidate/gpdb4/pljava/pljava-(.*)-rhel5-x86_64.gppkg

- name: pljava_gpdb4_sles11_release_candidate
  type: s3
  source:
    bucket: {{pl-bucket-name}}
    region_name: {{aws-region}}
    access_key_id: {{bucket-access-key-id}}
    secret_access_key: {{bucket-secret-access-key}}
    regexp: release_candidate/gpdb4/pljava/pljava-(.*)-sles11-x86_64.gppkg

jobs:
- name: pljava_gpdb4_centos5_build
  plan:
  - aggregate:
    - get: pljava_src
      trigger: true
    - get: bin_gpdb
      trigger: true
      resource: bin_gpdb4_centos5
    - get: pljava_centos5_img
    - get: jre
  - aggregate:
    - task: pljava_gpdb4_build
      file: pljava_src/concourse/tasks/build_pljava.yml
      image: pljava_centos5_img
      params:
        OSVER: centos5
        PL_GP_VERSION: "4.3"
  - aggregate:
    - put: pljava_gpdb4_centos5_build
      params:
        file: pljava_gppkg/pljava-*.gppkg

- name: pljava_gpdb4_sles11_build
  plan:
  - aggregate:
    - get: pljava_src
      trigger: true
    - get: bin_gpdb
      trigger: true
      resource: bin_gpdb4_sles11
    - get: jre
  - aggregate:
    - task: pljava_gpdb_build
      file: pljava_src/concourse/tasks/build_pljava_sles.yml
      params:
        OSVER: suse11
        PL_GP_VERSION: "4.3"
  - aggregate:
    - put: pljava_gpdb4_sles11_build
      params:
        file: pljava_gppkg/pljava-*.gppkg

- name: pljava_gpdb4_centos5_test
  plan:
  - aggregate:
    - get: pljava_src
      passed: [pljava_gpdb4_centos5_build]
    - get: pljava_bin
      passed: [pljava_gpdb4_centos5_build]
      trigger: true
      resource: pljava_gpdb4_centos5_build
    - get: bin_gpdb
      resource: bin_gpdb4_centos5
    - get: pljava_centos5_img
    - get: gpdb_src
  - aggregate:
    - task: test_pljava
      file: pljava_src/concourse/tasks/test_pljava.yml
      image: pljava_centos5_img
      params:
        OSVER: centos5

- name: pljava_gpdb4_sles11_test
  plan:
  - aggregate:
    - get: pljava_src
      passed: [pljava_gpdb4_sles11_build]
    - get: pljava_bin
      passed: [pljava_gpdb4_sles11_build]
      trigger: true
      resource: pljava_gpdb4_sles11_build
    - get: bin_gpdb
      resource: bin_gpdb4_sles11
    - get: gpdb_src
  - aggregate:
    - task: test_pljava
      file: pljava_src/concourse/tasks/test_pljava_sles.yml
      params:
        OSVER: suse11

- name: pljava_gpdb4_centos5_release
  plan:
  - aggregate:
    - get: pljava_bin
      resource: pljava_gpdb4_centos5_build
    - get: pljava_src
      trigger: true
      resource: release_src
    - get: pljava_centos5_img
  - aggregate:
    - task: release_pljava
      file: pljava_src/concourse/tasks/release_pljava.yml
      image: pljava_centos5_img
      params:
        OSVER: centos5
  - aggregate:
    - put: pljava_gpdb4_centos5_release_candidate
      params:
        file: pljava_gppkg/pljava-*.gppkg

- name: pljava_gpdb4_sles11_release
  plan:
  - aggregate:
    - get: pljava_bin
      resource: pljava_gpdb4_sles11_build
    - get: pljava_src
      trigger: true
      resource: release_src
  - aggregate:
    - task: release_pljava
      file: pljava_src/concourse/tasks/release_pljava_sles.yml
      params:
        OSVER: suse11
  - aggregate:
    - put: pljava_gpdb4_sles11_release_candidate
      params:
        file: pljava_gppkg/pljava-*.gppkg

- name: pljava_gpdb4_centos5_release_test
  plan:
  - aggregate:
    - get: pljava_src
      resource: release_src
    - get: pljava_bin
      resource: pljava_gpdb4_centos5_release
    - get: bin_gpdb
      trigger: true
      resource: bin_gpdb4_centos5
    - get: pljava_centos5_img
    - get: gpdb_src
  - aggregate:
    - task: test_pljava
      file: pljava_src/concourse/tasks/test_pljava.yml
      image: pljava_centos5_img
      params:
        OSVER: centos5

- name: pljava_gpdb4_sles11_release_test
  plan:
  - aggregate:
    - get: pljava_src
      resource: release_src
    - get: pljava_bin
      resource: pljava_gpdb4_sles11_release
    - get: bin_gpdb
      trigger: true
      resource: bin_gpdb4_sles11
    - get: gpdb_src
  - aggregate:
    - task: test_pljava
      file: pljava_src/concourse/tasks/test_pljava_sles.yml
      params:
        OSVER: suse11
