
## ======================================================================
## Pipeline for GPDB6 PL/JAVA GPPKG
## ======================================================================

groups:
- name: All
  jobs:
    - pljava_rhel8_build
    - pljava_centos7_build
    - pljava_centos6_build
    - pljava_ubuntu18_build
    - pljava_rhel8_release
    - pljava_centos7_release
    - pljava_centos6_release
    - pljava_ubuntu18_release
    - pljava_rhel8_test_release
    - pljava_centos7_test_release
    - pljava_centos6_test_release
    - pljava_ubuntu18_test_release
    - manual_push_rhel8_release
    - manual_push_centos7_release
    - manual_push_centos6_release
    - manual_push_ubuntu18_release

- name: GPDB6
  jobs:
    - pljava_rhel8_build
    - pljava_centos7_build
    - pljava_centos6_build
    - pljava_ubuntu18_build

- name: RELEASE
  jobs:
    - pljava_rhel8_release
    - pljava_centos7_release
    - pljava_centos6_release
    - pljava_ubuntu18_release
    - manual_push_rhel8_release
    - manual_push_centos7_release
    - manual_push_centos6_release
    - manual_push_ubuntu18_release

- name: TEST_RELEASE
  jobs:
    - pljava_rhel8_test_release
    - pljava_centos7_test_release
    - pljava_centos6_test_release
    - pljava_ubuntu18_test_release

## ===================
## params
## ===================
centos6_params: &centos6_params
  OSVER: centos6
  BLDARCH: rhel6_x86_64
  PL_GP_VERSION: "6.0"
centos7_params: &centos7_params
  OSVER: centos7
  BLDARCH: rhel7_x86_64
  PL_GP_VERSION: "6.0"
ubuntu18_params: &ubuntu18_params
  OSVER: ubuntu18
  BLDARCH: ubuntu18_amd64
  PL_GP_VERSION: "6.0"
rhel8_params: &rhel8_params
  OSVER: rhel8
  BLDARCH: rhel8_amd64
  PL_GP_VERSION: "6.0"

resource_types:
- name: gcs
  type: registry-image
  source:
    repository: frodenas/gcs-resource

## ======================================================================
## resources
## ======================================================================
resources:

## GPDB6 resource
##
- name: bin_gpdb_centos6
  type: gcs
  source:
    bucket: ((gcs-bucket-intermediates))
    json_key: ((concourse-gcs-resources-service-account-key))
    versioned_file: 6X_STABLE/bin_gpdb_centos6/bin_gpdb.tar.gz

- name: bin_gpdb_rhel8
  type: gcs
  source:
    bucket: {{gcs-bucket-intermediates}}
    json_key: {{concourse-gcs-resources-service-account-key}}
    versioned_file: ((gcs_gpdb_binary_folder))/bin_gpdb_rhel8/bin_gpdb.tar.gz

- name: bin_gpdb_centos7
  type: gcs
  source:
    bucket: ((gcs-bucket-intermediates))
    json_key: ((concourse-gcs-resources-service-account-key))
    versioned_file: 6X_STABLE/bin_gpdb_centos7/bin_gpdb.tar.gz

- name: bin_gpdb_ubuntu18
  type: gcs
  source:
    bucket: ((gcs-bucket-intermediates))
    json_key: ((concourse-gcs-resources-service-account-key))
    versioned_file: 6X_STABLE/bin_gpdb_ubuntu18.04/bin_gpdb.tar.gz

- name: pljava_centos6_img
  type: registry-image
  source:
    repository: gcr.io/data-gpdb-public-images/gpdb5-centos6-build-test
    tag: latest

- name: pljava_rhel8_image_test
  type: registry-image
  source:
    repository: gcr.io/data-gpdb-private-images/gpdb6-rhel8-test
    tag: latest
    username: _json_key
    password: ((container-registry-readonly-service-account-key))

- name: pljava_rhel8_image_build
  type: registry-image
  source:
    repository: gcr.io/data-gpdb-private-images/gpdb6-rhel8-build
    tag: latest
    username: _json_key
    password: ((container-registry-readonly-service-account-key))

- name: pljava_centos7_img
  type: registry-image
  source:
    repository: gcr.io/data-gpdb-public-images/gpdb5-centos7-build-test
    tag: latest

- name: pljava_ubuntu18_img
  type: registry-image
  source:
    repository: gcr.io/data-gpdb-public-images/gpdb6-ubuntu18.04-build
    tag: latest

- name: pljava_ubuntu18_img_test
  type: registry-image
  source:
    repository: gcr.io/data-gpdb-public-images/gpdb6-ubuntu18.04-test
    tag: latest

- name: pljava_src
  type: git
  source:
    branch: gpdb6_release
    uri: https://github.com/greenplum-db/pljava.git

- name: gpdb_src
  type: git
  source:
    branch: ((gpdb-git-branch))
    uri: https://github.com/greenplum-db/gpdb.git

- name: release_trigger
  type: git
  source:
    branch: gpdb6_release
    uri: https://github.com/greenplum-db/pljava.git
    tag_filter: 2.*

- name: pljava_gpdb_centos6_build
  type: gcs
  source:
    bucket: ((gcs-bucket-intermediates))
    json_key: ((concourse-gcs-resources-service-account-key))
    regexp: pljava/published/gpdb6/pljava-rhel6.gppkg

- name: pljava_gpdb_centos7_build
  type: gcs
  source:
    bucket: ((gcs-bucket-intermediates))
    json_key: ((concourse-gcs-resources-service-account-key))
    regexp: pljava/published/gpdb6/pljava-rhel7.gppkg

- name: pljava_gpdb_rhel8_build
  type: gcs
  source:
    bucket: ((gcs-bucket-intermediates))
    json_key: ((concourse-gcs-resources-service-account-key))
    regexp: pljava/published/gpdb6/pljava-rhel8.gppkg

- name: pljava_gpdb_ubuntu18_build
  type: gcs
  source:
    bucket: ((gcs-bucket-intermediates))
    json_key: ((concourse-gcs-resources-service-account-key))
    regexp: pljava/published/gpdb6/pljava-ubuntu18.gppkg

- name: pljava_gpdb_centos6_release
  type: gcs
  source:
    bucket: ((gcs-bucket))
    json_key: ((concourse-gcs-resources-service-account-key))
    regexp: pljava/released/gpdb6/pljava-(.*)-rhel6_x86_64.gppkg

- name: pljava_gpdb_centos7_release
  type: gcs
  source:
    bucket: ((gcs-bucket))
    json_key: ((concourse-gcs-resources-service-account-key))
    regexp: pljava/released/gpdb6/pljava-(.*)-rhel7_x86_64.gppkg

- name: pljava_gpdb_rhel8_release
  type: gcs
  source:
    bucket: ((gcs-bucket))
    json_key: ((concourse-gcs-resources-service-account-key))
    regexp: pljava/released/gpdb6/pljava-(.*)-rhel8_x86_64.gppkg

- name: pljava_gpdb_ubuntu18_release
  type: gcs
  source:
    bucket: ((gcs-bucket))
    json_key: ((concourse-gcs-resources-service-account-key))
    regexp: pljava/released/gpdb6/pljava-(.*)-ubuntu18.04_x86_64.gppkg

- name: pljava_gpdb_centos6_release_candidate
  type: gcs
  source:
    bucket: ((gcs-bucket-intermediates))
    json_key: ((concourse-gcs-resources-service-account-key))
    regexp: pljava/release_candidate/gpdb6/pljava-(.*)-rhel6_x86_64.gppkg

- name: pljava_gpdb_centos7_release_candidate
  type: gcs
  source:
    bucket: ((gcs-bucket-intermediates))
    json_key: ((concourse-gcs-resources-service-account-key))
    regexp: pljava/release_candidate/gpdb6/pljava-(.*)-rhel7_x86_64.gppkg

- name: pljava_gpdb_rhel8_release_candidate
  type: gcs
  source:
    bucket: ((gcs-bucket-intermediates))
    json_key: ((concourse-gcs-resources-service-account-key))
    regexp: pljava/release_candidate/gpdb6/pljava-(.*)-rhel8_x86_64.gppkg

- name: pljava_gpdb_ubuntu18_release_candidate
  type: gcs
  source:
    bucket: ((gcs-bucket-intermediates))
    json_key: ((concourse-gcs-resources-service-account-key))
    regexp: pljava/release_candidate/gpdb6/pljava-(.*)-ubuntu18.04_x86_64.gppkg

- name: jdk11_tgz
  type: gcs
  source:
    bucket: ((gcs-bucket))
    json_key: ((concourse-gcs-resources-service-account-key))
    regexp: pljava/dependency/gpdb6/openjdk-(.*)_linux-x64_bin.tar.gz

jobs:
## GPDB6 PL/Java Jobs
- name: pljava_rhel8_build
  plan:
  - aggregate:
    - get: pljava_src
      trigger: true
    - get: bin_gpdb
      resource: bin_gpdb_rhel8
      trigger: true
    - get: pljava_rhel8_image_build
    - get: pljava_rhel8_image_test
    - get: gpdb_src
  - aggregate:
    - task: pljava_gpdb_build
      file: pljava_src/concourse/tasks/build_pljava.yml
      image: pljava_rhel8_image_build
      params:
        <<: *rhel8_params
        JDK_VERSION: 8
  - aggregate:
    - task: test_java8
      file: pljava_src/concourse/tasks/test_pljava.yml
      image: pljava_rhel8_image_test
      input_mapping:
        pljava_bin: pljava_gppkg
      params:
        <<: *rhel8_params
        JDK_VERSION: 8
    - task: test_java11
      file: pljava_src/concourse/tasks/test_pljava.yml
      image: pljava_rhel8_image_test
      input_mapping:
        pljava_bin: pljava_gppkg
      params:
        <<: *rhel8_params
        JDK_VERSION: 11
  - aggregate:
    - put: pljava_gpdb_rhel8_build
      params:
        file: pljava_gppkg/pljava-*.gppkg

- name: pljava_centos7_build
  plan:
  - aggregate:
    - get: pljava_src
      trigger: true
    - get: bin_gpdb
      resource: bin_gpdb_centos7
      trigger: true
    - get: pljava_centos7_img
    - get: gpdb_src
  - aggregate:
    - task: pljava_gpdb_build
      file: pljava_src/concourse/tasks/build_pljava.yml
      image: pljava_centos7_img
      params:
        <<: *centos7_params
        JDK_VERSION: 8
  - aggregate:
    - task: test_java8
      file: pljava_src/concourse/tasks/test_pljava.yml
      image: pljava_centos7_img
      input_mapping:
        pljava_bin: pljava_gppkg
      params:
        <<: *centos7_params
        JDK_VERSION: 8
    - task: test_java11
      file: pljava_src/concourse/tasks/test_pljava.yml
      image: pljava_centos7_img
      input_mapping:
        pljava_bin: pljava_gppkg
      params:
        <<: *centos7_params
        JDK_VERSION: 11
  - aggregate:
    - put: pljava_gpdb_centos7_build
      params:
        file: pljava_gppkg/pljava-*.gppkg

- name: pljava_centos6_build
  plan:
  - aggregate:
    - get: pljava_src
      trigger: true
    - get: bin_gpdb
      resource: bin_gpdb_centos6
      trigger: true
    - get: pljava_centos6_img
    - get: gpdb_src
    - get: jdk_bin
      resource: jdk11_tgz
  - aggregate:
    - task: pljava_gpdb_build
      file: pljava_src/concourse/tasks/build_pljava.yml
      image: pljava_centos6_img
      params:
        <<: *centos6_params
        JDK_VERSION: 8
  - aggregate:
    - task: test_java8
      file: pljava_src/concourse/tasks/test_pljava.yml
      image: pljava_centos6_img
      input_mapping:
        pljava_bin: pljava_gppkg
      params:
        <<: *centos6_params
        JDK_VERSION: 8
    - task: test_java11
      file: pljava_src/concourse/tasks/test_pljava_jdk.yml
      image: pljava_centos6_img
      input_mapping:
        pljava_bin: pljava_gppkg
      params:
        <<: *centos6_params
        JDK_VERSION: 11
  - aggregate:
    - put: pljava_gpdb_centos6_build
      params:
        file: pljava_gppkg/pljava-*.gppkg

- name: pljava_ubuntu18_build
  plan:
  - aggregate:
    - get: pljava_src
      trigger: true
    - get: bin_gpdb
      resource: bin_gpdb_ubuntu18
      trigger: true
    - get: pljava_ubuntu18_img
    - get: pljava_ubuntu18_img_test
    - get: gpdb_src
  - aggregate:
    - task: pljava_gpdb_build
      file: pljava_src/concourse/tasks/build_pljava.yml
      image: pljava_ubuntu18_img
      params:
        <<: *ubuntu18_params
        JDK_VERSION: 8
  - aggregate:
    - task: test_java8
      file: pljava_src/concourse/tasks/test_pljava.yml
      image: pljava_ubuntu18_img_test
      input_mapping:
        pljava_bin: pljava_gppkg
      params:
        <<: *ubuntu18_params
        JDK_VERSION: 8
    - task: test_java11
      file: pljava_src/concourse/tasks/test_pljava.yml
      image: pljava_ubuntu18_img_test
      input_mapping:
        pljava_bin: pljava_gppkg
      params:
        <<: *ubuntu18_params
        JDK_VERSION: 11
  - aggregate:
    - put: pljava_gpdb_ubuntu18_build
      params:
        file: pljava_gppkg/pljava-*.gppkg

- name: pljava_rhel8_test_release
  plan:
  - aggregate:
    - get: pljava_src
      resource: release_trigger
    - get: pljava_bin
      resource: pljava_gpdb_rhel8_release
    - get: bin_gpdb
      resource: bin_gpdb_rhel8
      trigger: true
    - get: pljava_rhel8_image_test
    - get: gpdb_src
  - aggregate:
    - task: test_java8
      file: pljava_src/concourse/tasks/test_pljava.yml
      image: pljava_rhel8_image_test
      params:
        <<: *rhel8_params
        JDK_VERSION: 8
    - task: test_java11
      file: pljava_src/concourse/tasks/test_pljava.yml
      image: pljava_rhel8_image_test
      params:
        <<: *rhel8_params
        JDK_VERSION: 11

- name: pljava_centos7_test_release
  plan:
  - aggregate:
    - get: pljava_src
      resource: release_trigger
    - get: pljava_bin
      resource: pljava_gpdb_centos7_release
    - get: bin_gpdb
      resource: bin_gpdb_centos7
      trigger: true
    - get: pljava_centos7_img
    - get: gpdb_src
  - aggregate:
    - task: test_java8
      file: pljava_src/concourse/tasks/test_pljava.yml
      image: pljava_centos7_img
      params:
        <<: *centos7_params
        JDK_VERSION: 8
    - task: test_java11
      file: pljava_src/concourse/tasks/test_pljava.yml
      image: pljava_centos7_img
      params:
        <<: *centos7_params
        JDK_VERSION: 11

- name: pljava_centos6_test_release
  plan:
  - aggregate:
    - get: pljava_src
      resource: release_trigger
    - get: pljava_bin
      resource: pljava_gpdb_centos6_release
    - get: bin_gpdb
      resource: bin_gpdb_centos6
      trigger: true
    - get: pljava_centos6_img
    - get: gpdb_src
    - get: jdk_bin
      resource: jdk11_tgz
  - aggregate:
    - task: test_java8
      file: pljava_src/concourse/tasks/test_pljava.yml
      image: pljava_centos6_img
      params:
        <<: *centos6_params
        JDK_VERSION: 8
    - task: test_java11
      file: pljava_src/concourse/tasks/test_pljava_jdk.yml
      image: pljava_centos6_img
      params:
        <<: *centos6_params
        JDK_VERSION: 11

- name: pljava_ubuntu18_test_release
  plan:
  - aggregate:
    - get: pljava_src
      resource: release_trigger
    - get: pljava_bin
      resource: pljava_gpdb_ubuntu18_release
    - get: bin_gpdb
      resource: bin_gpdb_ubuntu18
      trigger: true
    - get: pljava_ubuntu18_img_test
    - get: gpdb_src
  - aggregate:
    - task: test_java8
      file: pljava_src/concourse/tasks/test_pljava.yml
      image: pljava_ubuntu18_img_test
      params:
        <<: *ubuntu18_params
        JDK_VERSION: 8
    - task: test_java11
      file: pljava_src/concourse/tasks/test_pljava.yml
      image: pljava_ubuntu18_img_test
      params:
        <<: *ubuntu18_params
        JDK_VERSION: 11

- name: pljava_rhel8_release
  plan:
  - aggregate:
    - get: pljava_src
      resource: release_trigger
      trigger: true
    - get: pljava_bin
      resource: pljava_gpdb_rhel8_build
    - get: pljava_rhel8_image_test
  - aggregate:
    - task: release_pljava
      file: pljava_src/concourse/tasks/release_pljava.yml
      image: pljava_rhel8_image_test
      params:
        <<: *rhel8_params
  - aggregate:
    - put: pljava_gpdb_rhel8_release_candidate
      params:
        file: pljava_gppkg/pljava-*.gppkg

- name: pljava_centos7_release
  plan:
  - aggregate:
    - get: pljava_src
      resource: release_trigger
      trigger: true
    - get: pljava_bin
      resource: pljava_gpdb_centos7_build
    - get: pljava_centos7_img
  - aggregate:
    - task: release_pljava
      file: pljava_src/concourse/tasks/release_pljava.yml
      image: pljava_centos7_img
      params:
        <<: *centos7_params
  - aggregate:
    - put: pljava_gpdb_centos7_release_candidate
      params:
        file: pljava_gppkg/pljava-*.gppkg

- name: pljava_centos6_release
  plan:
  - aggregate:
    - get: pljava_src
      resource: release_trigger
      trigger: true
    - get: pljava_bin
      resource: pljava_gpdb_centos6_build
    - get: pljava_centos6_img
  - aggregate:
    - task: release_pljava
      file: pljava_src/concourse/tasks/release_pljava.yml
      image: pljava_centos6_img
      params:
        <<: *centos6_params
  - aggregate:
    - put: pljava_gpdb_centos6_release_candidate
      params:
        file: pljava_gppkg/pljava-*.gppkg

- name: pljava_ubuntu18_release
  plan:
  - aggregate:
    - get: pljava_src
      resource: release_trigger
      trigger: true
    - get: pljava_bin
      resource: pljava_gpdb_ubuntu18_build
    - get: pljava_ubuntu18_img_test
  - aggregate:
    - task: release_pljava
      file: pljava_src/concourse/tasks/release_pljava.yml
      image: pljava_ubuntu18_img_test
      params:
        <<: *ubuntu18_params
  - aggregate:
    - put: pljava_gpdb_ubuntu18_release_candidate
      params:
        file: pljava_gppkg/pljava-*.gppkg

- name: manual_push_rhel8_release
  plan:
  - aggregate:
    - get: pljava_rhel8_image_test
      trigger: false
    - get: pljava_gpdb_rhel8_release_candidate
      trigger: false
  - task: Copy_GPPKG
    image: pljava_rhel8_image_test
    config:
      platform: linux
      inputs:
       - name: pljava_gpdb_rhel8_release_candidate
      outputs:
       - name: pljava_gpdb_rhel8_release
      run:
          path: "sh"
          args:
            - -exc
            - |
              cp pljava_gpdb_rhel8_release_candidate/pljava-*.gppkg pljava_gpdb_rhel8_release/
  - put: pljava_gpdb_rhel8_release
    params:
      file: pljava_gpdb_rhel8_release/pljava-*.gppkg

- name: manual_push_centos7_release
  plan:
  - aggregate:
    - get: pljava_centos7_img
      trigger: false
    - get: pljava_gpdb_centos7_release_candidate
      trigger: false
  - task: Copy_GPPKG
    image: pljava_centos7_img
    config:
      platform: linux
      inputs:
       - name: pljava_gpdb_centos7_release_candidate
      outputs:
       - name: pljava_gpdb_centos7_release
      run:
          path: "sh"
          args:
            - -exc
            - |
              cp pljava_gpdb_centos7_release_candidate/pljava-*.gppkg pljava_gpdb_centos7_release/
  - put: pljava_gpdb_centos7_release
    params:
      file: pljava_gpdb_centos7_release/pljava-*.gppkg

- name: manual_push_centos6_release
  plan:
  - aggregate:
    - get: pljava_centos6_img
      trigger: false
    - get: pljava_gpdb_centos6_release_candidate
      trigger: false
  - task: Copy_GPPKG
    image: pljava_centos6_img
    config:
      platform: linux
      inputs:
       - name: pljava_gpdb_centos6_release_candidate
      outputs:
       - name: pljava_gpdb_centos6_release
      run:
          path: "sh"
          args:
            - -exc
            - |
              cp pljava_gpdb_centos6_release_candidate/pljava-*.gppkg pljava_gpdb_centos6_release/
  - put: pljava_gpdb_centos6_release
    params:
      file: pljava_gpdb_centos6_release/pljava-*.gppkg

- name: manual_push_ubuntu18_release
  plan:
  - aggregate:
    - get: pljava_ubuntu18_img_test
      trigger: false
    - get: pljava_gpdb_ubuntu18_release_candidate
      trigger: false
  - task: Copy_GPPKG
    image: pljava_ubuntu18_img_test
    config:
      platform: linux
      inputs:
       - name: pljava_gpdb_ubuntu18_release_candidate
      outputs:
       - name: pljava_gpdb_ubuntu18_release
      run:
          path: "sh"
          args:
            - -exc
            - |
              cp pljava_gpdb_ubuntu18_release_candidate/pljava-*.gppkg pljava_gpdb_ubuntu18_release/
  - put: pljava_gpdb_ubuntu18_release
    params:
      file: pljava_gpdb_ubuntu18_release/pljava-*.gppkg
