platform: linux

image_resource:
  type: docker-image
  source:
    repository: pivotaldata/sles-gpdb-dev
    tag: '11-beta'
inputs:
  - name: bin_gpdb
  - name: pljava_src
  - name: pljava_bin
  - name: gpdb_src

run:
  path: pljava_src/concourse/scripts/test_pljava.sh

params: 
  OSVER:
